export const Logo = ({ className = '' }: { className?: string }) => {
  return (
    <svg
      className={`text-foreground transition-colors duration-300 ${className}`}
      xmlns="http://www.w3.org/2000/svg"
      width="512"
      height="512"
      viewBox="0 0 512 512"
      fill="none"
      stroke="currentColor"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <circle
        cx="256"
        cy="256"
        r="160"
        className="stroke-current"
        strokeWidth="24"
        fill="none"
      />
      <line
        x1="350"
        y1="350"
        x2="450"
        y2="450"
        className="stroke-current"
        strokeWidth="24"
        strokeLinecap="round"
      />
      <rect
        x="185"
        y="190"
        width="60"
        height="100"
        fill="none"
        className="stroke-current"
        strokeWidth="10"
        rx="4"
      />
      <line
        x1="195"
        y1="200"
        x2="235"
        y2="200"
        className="stroke-current"
        strokeWidth="6"
      />
      <line
        x1="195"
        y1="215"
        x2="235"
        y2="215"
        className="stroke-current"
        strokeWidth="6"
      />
      <line
        x1="195"
        y1="230"
        x2="235"
        y2="230"
        className="stroke-current"
        strokeWidth="6"
      />
      <line
        x1="195"
        y1="245"
        x2="235"
        y2="245"
        className="stroke-current"
        strokeWidth="6"
      />
      <path
        d="M270 190 h50 v80 l-20 20 h-30 z"
        fill="none"
        className="stroke-current"
        strokeWidth="10"
      />
      <line
        x1="280"
        y1="210"
        x2="310"
        y2="210"
        className="stroke-current"
        strokeWidth="6"
      />
      <line
        x1="280"
        y1="225"
        x2="310"
        y2="225"
        className="stroke-current"
        strokeWidth="6"
      />
    </svg>
  )
}
